### ISSUE TITLE
CSV Result limit

### ISSUE THREAD

**Issue by rudnypc** [DeineAgenturUG/greenbone-gvm-openvas-for-docker#32]
Hi,

I have a problem my stacks, I'm missing some results, is this repo fixed this problem https://community.greenbone.net/t/exported-reports-missing-most-of-the-results/2876 ?

**Comment by Dexus** [comment]
Hi @rudnypc 

I'm not sure, what the problem was, not even there is any solution in the topic.
So I'm not aware of any problem with it yet. But I'm also only use the source from Greenbone and don't fix things my self, except of what I can do with this Docker Image.

Regards, Josef

**Comment by Dexus** [comment]
Hi again @rudnypc,

I have just read it again and I think this fix script (https://github.com/DeineAgenturUG/greenbone-gvm-openvas-for-docker/blob/main/GVMDocker/scripts/reportFix.sh) is what you mean. And no, we don't fix it automatically on setup, because it has performance impact, and I don't touch things if they have negative impact of performance.

Regards, Josef
